// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEO17H_pAbLktzubqvq5kt32nJMFlr9V0',
    appId: '1:899195973843:web:0cfc2bf5c92b3e14bea426',
    messagingSenderId: '899195973843',
    projectId: 'capstone2-1ad1d',
    authDomain: 'capstone2-1ad1d.firebaseapp.com',
    storageBucket: 'capstone2-1ad1d.appspot.com',
    measurementId: 'G-GC66C0P2H3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHJx9XWAVFwk3uMgwDv1tLJlEfRbHhHC8',
    appId: '1:899195973843:android:5458170ef6c3049bbea426',
    messagingSenderId: '899195973843',
    projectId: 'capstone2-1ad1d',
    storageBucket: 'capstone2-1ad1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsv0UZQuyzdClHrmKgD70c128Z5YTgFd4',
    appId: '1:899195973843:ios:d1307f446116e6d8bea426',
    messagingSenderId: '899195973843',
    projectId: 'capstone2-1ad1d',
    storageBucket: 'capstone2-1ad1d.appspot.com',
    iosClientId: '899195973843-qnjg7lborg4usfd6j49020ei9ve8vag2.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstone',
  );
}
